-- First create whopipe_video_views which has 4 columns
-- 'If NOT EXISTS' prevents the CREATE TABLE being attempted if table name already exists
CREATE TABLE IF NOT EXISTS whopipe_video_views (
    view_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    video_name TEXT NOT NULL,
    region TEXT NOT NULL,
    date_viewed TIMESTAMP DEFAULT now() NOT NULL
);

-- Second and third instances create a new type called department which is ENUM
-- ENUM is a list of options that may be used as columns in table rows
-- CREATE TYPE doesnt'support DOES NOT EXISTS so instead we remove the type if it does exist first.
DROP TYPE IF EXISTS department;
CREATE TYPE department AS ENUM (
    'Electronics',
    'Cleaning',
    'Grocery',
    'Furniture',
    'Stationery',
    'Clothing',
    'DIY',
    'Sports',
    'Homeware',
    'Games',
    'Transport'
);

-- Create a table called amazong_products; the table has 5 columns
-- Price is set to decimal which can be 12 in "precision" and 2 decimal points
-- Category column has type department which is the ENUM that was created.
CREATE TABLE IF NOT EXISTS amazong_products (
    product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    image TEXT,
    category department NOT NULL
);